# Generated by Django 4.2.5 on 2023-10-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_user_comment_profile_rename_user_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvote_count',
            new_name='like_count',
        ),
    ]
