# Generated by Django 4.2.5 on 2023-10-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_image_profile_profile_pic_url_and_more'),
        ('posts', '0004_rename_upvote_count_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked', to='profiles.profile'),
        ),
    ]
