# Generated by Django 4.2.5 on 2023-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_image_profile_profile_pic_url_and_more'),
        ('posts', '0005_remove_post_like_count_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='profiles.profile'),
        ),
    ]
