# Generated by Django 4.2.5 on 2023-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_image_profile_profile_pic_url_and_more'),
        ('posts', '0007_alter_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
