# Generated by Django 4.2.5 on 2024-03-01 16:29

from django.db import migrations, models
import django_advance_thumbnail.fields
import posts.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to=posts.models.upload_to),
        ),
        migrations.AddField(
            model_name='postimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=posts.models.upload_to),
        ),
    ]
