# Generated by Django 4.2.5 on 2024-03-01 16:43

from django.db import migrations
import django_advance_thumbnail.fields
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postimage_thumbnail_postimage_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to=posts.models.upload_to_thumbnail),
        ),
    ]
