# Generated by Django 5.0.4 on 2024-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_postimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
