# Generated by Django 4.2.5 on 2023-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_user_comment_profile_rename_user_post_profile'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='posts.post'),
        ),
    ]
