# Generated by Django 4.2.5 on 2023-11-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_profile_pic_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic_url',
            new_name='profile_pic',
        ),
    ]
