# Generated by Django 4.2.5 on 2023-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_profile_pic_url_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.SlugField(default='ok', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
