services:
  django:
    build: .
    container_name: ig-api
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    # serve root dir to /code
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16.3
    container_name: ig-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    container_name: ig-pgadmin
    ports:
      - 8888:80
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  postgres_data: