# Generated by Django 4.2.5 on 2023-10-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
